FROM ubuntu

# You don't need to install all this, it's just helpful for debugging
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    strace \
    \
  && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/webdestroya/remote-shell:latest /cloud87 /cloud87

