name: "Docker"

# Only trigger if we changed the files used in the image
on:
  release:
    types:
      - published

jobs:
  docker-release:
    name: "Release Docker Image"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: Prepare Tags
        id: prepare
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          MAJOR_MINOR=${TAG%.*}
          MAJOR_ONLY=${TAG%.*.*}
          SHORT_COMMIT=${GITHUB_SHA::8}
          echo ::set-output name=tag_name::${TAG}
          echo ::set-output name=major_tag::${MAJOR_ONLY}
          echo ::set-output name=major_minor_tag::${MAJOR_MINOR}
          echo ::set-output name=short_commit::${SHORT_COMMIT}
          echo ::set-output name=full_tag_name::${TAG}
          echo ::set-output name=full_major_tag::${MAJOR_ONLY}
          echo ::set-output name=full_major_minor_tag::${MAJOR_MINOR}
          echo ::set-output name=latest_tag::latest

      
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and publish
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            RSHELL_VERSION=${{ steps.prepare.outputs.tag_name }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.prepare.outputs.full_tag_name }}
            ghcr.io/${{ github.repository }}:${{ steps.prepare.outputs.full_major_tag }}
            ghcr.io/${{ github.repository }}:${{ steps.prepare.outputs.full_major_minor_tag }}
            ghcr.io/${{ github.repository }}:${{ steps.prepare.outputs.latest_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      