name: "Main"

# on:
#   pull_request:
#     types:
#       - opened
#       - reopened

on:
  workflow_call:
  pull_request:
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Display Go Version
        run: go version
        
      - name: Build
        run: go build -a -v
      
      - name: Smoke Test
        run: ./remote-shell -version && ./remote-shell --help
